@Library('enkins-Governance-Pipelines@main') _

runCIPipeline   staticCodeAnalysis: "",
                compileCommands: "mvn -B -DskipTests clean package",
                testCommands: "mvn test",
                jenkinsAgent "any"